package model.enums;

public enum ExceptionEnum {
    PERSIST_UNSUCCESSFULLY,
    ITEM_NFOUND,
    DELETE_UNSUCCESSFULLY,
    UPDATE_UNSUCCESSFULLY,
    CREATE_UNSUCCESSFULLY,
    INVALID_OPTION,UNDER_AGE_EXCEPTION
}